
package com.qbe.cotizador.servicios.QBE.emisionVehiculosWS;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

import com.qbe.cotizador.dao.seguridad.VariableSistemaDAO;
import com.qbe.cotizador.model.VariableSistema;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "EmisionQbeLink", targetNamespace = "http://wsqbelink.servicios.tandi.com/", wsdlLocation = "http://localhost:8087/ensurance/EmisionQbeLink?wsdl")
public class EmisionQbeLink_Service
    extends Service
{

    private final static URL EMISIONQBELINK_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(EmisionQbeLink_Service.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = EmisionQbeLink_Service.class.getResource(".");
            VariableSistemaDAO vsDAO=new VariableSistemaDAO();
            VariableSistema  vs=vsDAO.buscarPorNombre("URL_SERVICIO_EMISION");
            //url = new URL(baseUrl, "http://10.10.10.59:8087/ensurance/EmisionQbeLink?wsdl");
              url = new URL(baseUrl, vs.getValor());
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8087/ensurance/EmisionQbeLink?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        EMISIONQBELINK_WSDL_LOCATION = url;
    }

    public EmisionQbeLink_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EmisionQbeLink_Service() {
        super(EMISIONQBELINK_WSDL_LOCATION, new QName("http://wsqbelink.servicios.tandi.com/", "EmisionQbeLink"));
    }

    /**
     * 
     * @return
     *     returns EmisionQbeLink
     */
    @WebEndpoint(name = "EmisionQbeLinkPort")
    public EmisionQbeLink getEmisionQbeLinkPort() {
        return super.getPort(new QName("http://wsqbelink.servicios.tandi.com/", "EmisionQbeLinkPort"), EmisionQbeLink.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EmisionQbeLink
     */
    @WebEndpoint(name = "EmisionQbeLinkPort")
    public EmisionQbeLink getEmisionQbeLinkPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://wsqbelink.servicios.tandi.com/", "EmisionQbeLinkPort"), EmisionQbeLink.class, features);
    }

}
