
package com.qbe.cotizador.servicios.QBE.emisionVehiculosWS;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "EmisionQbeLink", targetNamespace = "http://wsqbelink.servicios.tandi.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EmisionQbeLink {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "retorno", targetNamespace = "")
    @RequestWrapper(localName = "emisionGeneral", targetNamespace = "http://wsqbelink.servicios.tandi.com/", className = "com.tandi.servicios.wsqbelink.EmisionGeneral")
    @ResponseWrapper(localName = "emisionGeneralResponse", targetNamespace = "http://wsqbelink.servicios.tandi.com/", className = "com.tandi.servicios.wsqbelink.EmisionGeneralResponse")
    public String emisionGeneral(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerPuertoTomcat", targetNamespace = "http://wsqbelink.servicios.tandi.com/", className = "com.tandi.servicios.wsqbelink.ObtenerPuertoTomcat")
    @ResponseWrapper(localName = "obtenerPuertoTomcatResponse", targetNamespace = "http://wsqbelink.servicios.tandi.com/", className = "com.tandi.servicios.wsqbelink.ObtenerPuertoTomcatResponse")
    public Integer obtenerPuertoTomcat();

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "autenticar", targetNamespace = "http://wsqbelink.servicios.tandi.com/", className = "com.tandi.servicios.wsqbelink.Autenticar")
    @ResponseWrapper(localName = "autenticarResponse", targetNamespace = "http://wsqbelink.servicios.tandi.com/", className = "com.tandi.servicios.wsqbelink.AutenticarResponse")
    public String autenticar(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
