
package com.qbe.cotizador.servicios.smartwork.workflow;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ExternalServiceSoap", targetNamespace = "http://smartwork.com.ec/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ExternalServiceSoap {


    /**
     * 
     * @param archivos
     * @param visadoDocumentos
     * @param username
     * @param destinatarios
     * @param documentos
     * @param token
     * @param deuda
     * @param datosFianza
     * @param workFlowType
     * @param entidades
     * @param solicitud
     * @return
     *     returns ec.com.smartwork.WorkFlowResult
     */
    @WebMethod(operationName = "CreateInstanceWF", action = "http://smartwork.com.ec/CreateInstanceWF")
    @WebResult(name = "CreateInstanceWFResult", targetNamespace = "http://smartwork.com.ec/")
    @RequestWrapper(localName = "CreateInstanceWF", targetNamespace = "http://smartwork.com.ec/", className = "ec.com.smartwork.CreateInstanceWF")
    @ResponseWrapper(localName = "CreateInstanceWFResponse", targetNamespace = "http://smartwork.com.ec/", className = "ec.com.smartwork.CreateInstanceWFResponse")
    public WorkFlowResult createInstanceWF(
        @WebParam(name = "Token", targetNamespace = "http://smartwork.com.ec/")
        String token,
        @WebParam(name = "Username", targetNamespace = "http://smartwork.com.ec/")
        String username,
        @WebParam(name = "WorkFlowType", targetNamespace = "http://smartwork.com.ec/")
        WorkFlowType workFlowType,
        @WebParam(name = "Solicitud", targetNamespace = "http://smartwork.com.ec/")
        QBESolicitudEmision solicitud,
        @WebParam(name = "Entidades", targetNamespace = "http://smartwork.com.ec/")
        QBEEntidad entidades,
        @WebParam(name = "Documentos", targetNamespace = "http://smartwork.com.ec/")
        ArrayOfQBEControlDocumentos documentos,
        @WebParam(name = "Deuda", targetNamespace = "http://smartwork.com.ec/")
        QBEDeuda deuda,
        @WebParam(name = "Destinatarios", targetNamespace = "http://smartwork.com.ec/")
        QBEDestinatario destinatarios,
        @WebParam(name = "DatosFianza", targetNamespace = "http://smartwork.com.ec/")
        QBEFianza datosFianza,
        @WebParam(name = "Archivos", targetNamespace = "http://smartwork.com.ec/")
        ArrayOfFileList archivos,
        @WebParam(name = "VisadoDocumentos", targetNamespace = "http://smartwork.com.ec/")
        ArrayOfDocumentList visadoDocumentos);

    /**
     * 
     * @param token
     * @param tipo
     * @return
     *     returns ec.com.smartwork.ArrayOfClassifier
     */
    @WebMethod(operationName = "GetClassificator", action = "http://smartwork.com.ec/GetClassificator")
    @WebResult(name = "GetClassificatorResult", targetNamespace = "http://smartwork.com.ec/")
    @RequestWrapper(localName = "GetClassificator", targetNamespace = "http://smartwork.com.ec/", className = "ec.com.smartwork.GetClassificator")
    @ResponseWrapper(localName = "GetClassificatorResponse", targetNamespace = "http://smartwork.com.ec/", className = "ec.com.smartwork.GetClassificatorResponse")
    public ArrayOfClassifier getClassificator(
        @WebParam(name = "Token", targetNamespace = "http://smartwork.com.ec/")
        String token,
        @WebParam(name = "Tipo", targetNamespace = "http://smartwork.com.ec/")
        ClassificationType tipo);

    /**
     * 
     * @param token
     * @param tipo
     * @return
     *     returns ec.com.smartwork.ArrayOfClassifier
     */
    @WebMethod(operationName = "GetAprovedUsersByRole", action = "http://smartwork.com.ec/GetAprovedUsersByRole")
    @WebResult(name = "GetAprovedUsersByRoleResult", targetNamespace = "http://smartwork.com.ec/")
    @RequestWrapper(localName = "GetAprovedUsersByRole", targetNamespace = "http://smartwork.com.ec/", className = "ec.com.smartwork.GetAprovedUsersByRole")
    @ResponseWrapper(localName = "GetAprovedUsersByRoleResponse", targetNamespace = "http://smartwork.com.ec/", className = "ec.com.smartwork.GetAprovedUsersByRoleResponse")
    public ArrayOfClassifier getAprovedUsersByRole(
        @WebParam(name = "Token", targetNamespace = "http://smartwork.com.ec/")
        String token,
        @WebParam(name = "Tipo", targetNamespace = "http://smartwork.com.ec/")
        RoleType tipo);

    /**
     * 
     * @param token
     * @param tipo
     * @return
     *     returns ec.com.smartwork.ArrayOfDocumentList
     */
    @WebMethod(operationName = "LoadDocumentsByClassificator", action = "http://smartwork.com.ec/LoadDocumentsByClassificator")
    @WebResult(name = "LoadDocumentsByClassificatorResult", targetNamespace = "http://smartwork.com.ec/")
    @RequestWrapper(localName = "LoadDocumentsByClassificator", targetNamespace = "http://smartwork.com.ec/", className = "ec.com.smartwork.LoadDocumentsByClassificator")
    @ResponseWrapper(localName = "LoadDocumentsByClassificatorResponse", targetNamespace = "http://smartwork.com.ec/", className = "ec.com.smartwork.LoadDocumentsByClassificatorResponse")
    public ArrayOfDocumentList loadDocumentsByClassificator(
        @WebParam(name = "Token", targetNamespace = "http://smartwork.com.ec/")
        String token,
        @WebParam(name = "Tipo", targetNamespace = "http://smartwork.com.ec/")
        ClassificationType tipo);

    /**
     * 
     * @param token
     * @param numero
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "DeleteSolicitud", action = "http://smartwork.com.ec/DeleteSolicitud")
    @WebResult(name = "DeleteSolicitudResult", targetNamespace = "http://smartwork.com.ec/")
    @RequestWrapper(localName = "DeleteSolicitud", targetNamespace = "http://smartwork.com.ec/", className = "ec.com.smartwork.DeleteSolicitud")
    @ResponseWrapper(localName = "DeleteSolicitudResponse", targetNamespace = "http://smartwork.com.ec/", className = "ec.com.smartwork.DeleteSolicitudResponse")
    public boolean deleteSolicitud(
        @WebParam(name = "Token", targetNamespace = "http://smartwork.com.ec/")
        String token,
        @WebParam(name = "Numero", targetNamespace = "http://smartwork.com.ec/")
        int numero);

}
