
package com.qbe.cotizador.servicios.QBE.clienteServiciosCotizador;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WebServiceCotizadorAgricolaInterface", targetNamespace = "http://cotizador.interfaces.servicios.qbe.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface WebServiceCotizadorAgricolaInterface {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "retorno", partName = "retorno")
    @Action(input = "http://cotizador.interfaces.servicios.qbe.com/WebServiceCotizadorAgricolaInterface/obtenerCoberturasRequest", output = "http://cotizador.interfaces.servicios.qbe.com/WebServiceCotizadorAgricolaInterface/obtenerCoberturasResponse")
    public String obtenerCoberturas();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "retorno", partName = "retorno")
    @Action(input = "http://cotizador.interfaces.servicios.qbe.com/WebServiceCotizadorAgricolaInterface/obteneProductosRequest", output = "http://cotizador.interfaces.servicios.qbe.com/WebServiceCotizadorAgricolaInterface/obteneProductosResponse")
    public String obteneProductos();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "retorno", partName = "retorno")
    @Action(input = "http://cotizador.interfaces.servicios.qbe.com/WebServiceCotizadorAgricolaInterface/obtenerGruposCoberturaRequest", output = "http://cotizador.interfaces.servicios.qbe.com/WebServiceCotizadorAgricolaInterface/obtenerGruposCoberturaResponse")
    public String obtenerGruposCobertura();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "retorno", partName = "retorno")
    @Action(input = "http://cotizador.interfaces.servicios.qbe.com/WebServiceCotizadorAgricolaInterface/obtenerConjuntoCoberturasRequest", output = "http://cotizador.interfaces.servicios.qbe.com/WebServiceCotizadorAgricolaInterface/obtenerConjuntoCoberturasResponse")
    public String obtenerConjuntoCoberturas();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "retorno", partName = "retorno")
    @Action(input = "http://cotizador.interfaces.servicios.qbe.com/WebServiceCotizadorAgricolaInterface/obtenerDetallesProductoRequest", output = "http://cotizador.interfaces.servicios.qbe.com/WebServiceCotizadorAgricolaInterface/obtenerDetallesProductoResponse")
    public String obtenerDetallesProducto();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "retorno", partName = "retorno")
    @Action(input = "http://cotizador.interfaces.servicios.qbe.com/WebServiceCotizadorAgricolaInterface/obtenerCoberturaDetalleProductoRequest", output = "http://cotizador.interfaces.servicios.qbe.com/WebServiceCotizadorAgricolaInterface/obtenerCoberturaDetalleProductoResponse")
    public String obtenerCoberturaDetalleProducto();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "retorno", partName = "retorno")
    @Action(input = "http://cotizador.interfaces.servicios.qbe.com/WebServiceCotizadorAgricolaInterface/obtenerCoberturasConjuntoRequest", output = "http://cotizador.interfaces.servicios.qbe.com/WebServiceCotizadorAgricolaInterface/obtenerCoberturasConjuntoResponse")
    public String obtenerCoberturasConjunto();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "retorno", partName = "retorno")
    @Action(input = "http://cotizador.interfaces.servicios.qbe.com/WebServiceCotizadorAgricolaInterface/obtenerConfiguracionProductoRequest", output = "http://cotizador.interfaces.servicios.qbe.com/WebServiceCotizadorAgricolaInterface/obtenerConfiguracionProductoResponse")
    public String obtenerConfiguracionProducto();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "retorno", partName = "retorno")
    @Action(input = "http://cotizador.interfaces.servicios.qbe.com/WebServiceCotizadorAgricolaInterface/obtenerDeduciblesRequest", output = "http://cotizador.interfaces.servicios.qbe.com/WebServiceCotizadorAgricolaInterface/obtenerDeduciblesResponse")
    public String obtenerDeducibles();

}
