
package com.qbe.cotizador.servicios.QBE.clienteServiciosCotizador;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WebServiceCotizadorInterface", targetNamespace = "http://cotizador.interfaces.servicios.qbe.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface WebServiceCotizadorInterface {


    /**
     * 
     * @param identificacion
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "retorno", partName = "retorno")
    @Action(input = "http://cotizador.interfaces.servicios.qbe.com/WebServiceCotizadorInterface/datosUsuarioRequest", output = "http://cotizador.interfaces.servicios.qbe.com/WebServiceCotizadorInterface/datosUsuarioResponse")
    public String datosUsuario(
        @WebParam(name = "identificacion", partName = "identificacion")
        String identificacion);

    /**
     * 
     * @param placa
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "retorno", partName = "retorno")
    @Action(input = "http://cotizador.interfaces.servicios.qbe.com/WebServiceCotizadorInterface/obtenerNumeroReclamosPorPlacaRequest", output = "http://cotizador.interfaces.servicios.qbe.com/WebServiceCotizadorInterface/obtenerNumeroReclamosPorPlacaResponse")
    public int obtenerNumeroReclamosPorPlaca(
        @WebParam(name = "placa", partName = "placa")
        String placa);

    /**
     * 
     * @param nombreParametro
     * @param parametro
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "retorno", partName = "retorno")
    @Action(input = "http://cotizador.interfaces.servicios.qbe.com/WebServiceCotizadorInterface/obtenerDatosVehiculoRequest", output = "http://cotizador.interfaces.servicios.qbe.com/WebServiceCotizadorInterface/obtenerDatosVehiculoResponse")
    public String obtenerDatosVehiculo(
        @WebParam(name = "parametro", partName = "parametro")
        String parametro,
        @WebParam(name = "nombreParametro", partName = "nombreParametro")
        String nombreParametro);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "retorno", partName = "retorno")
    @Action(input = "http://cotizador.interfaces.servicios.qbe.com/WebServiceCotizadorInterface/obtenerCoberturasVHRequest", output = "http://cotizador.interfaces.servicios.qbe.com/WebServiceCotizadorInterface/obtenerCoberturasVHResponse")
    public String obtenerCoberturasVH();

    /**
     * 
     * @param numeroFactura
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "retorno", partName = "retorno")
    @Action(input = "http://cotizador.interfaces.servicios.qbe.com/WebServiceCotizadorInterface/obtenerEndosoIdPorNumerodeFacturaRequest", output = "http://cotizador.interfaces.servicios.qbe.com/WebServiceCotizadorInterface/obtenerEndosoIdPorNumerodeFacturaResponse")
    public String obtenerEndosoIdPorNumerodeFactura(
        @WebParam(name = "numeroFactura", partName = "numeroFactura")
        String numeroFactura);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "retorno", partName = "retorno")
    @Action(input = "http://cotizador.interfaces.servicios.qbe.com/WebServiceCotizadorInterface/obtenerGruposCoberturaVHRequest", output = "http://cotizador.interfaces.servicios.qbe.com/WebServiceCotizadorInterface/obtenerGruposCoberturaVHResponse")
    public String obtenerGruposCoberturaVH();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "retorno", partName = "retorno")
    @Action(input = "http://cotizador.interfaces.servicios.qbe.com/WebServiceCotizadorInterface/obteneProductosVHRequest", output = "http://cotizador.interfaces.servicios.qbe.com/WebServiceCotizadorInterface/obteneProductosVHResponse")
    public String obteneProductosVH();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "retorno", partName = "retorno")
    @Action(input = "http://cotizador.interfaces.servicios.qbe.com/WebServiceCotizadorInterface/obteneConjuntoCoberturasVHRequest", output = "http://cotizador.interfaces.servicios.qbe.com/WebServiceCotizadorInterface/obteneConjuntoCoberturasVHResponse")
    public String obteneConjuntoCoberturasVH();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "retorno", partName = "retorno")
    @Action(input = "http://cotizador.interfaces.servicios.qbe.com/WebServiceCotizadorInterface/obtenerCoberturasConjuntoVHRequest", output = "http://cotizador.interfaces.servicios.qbe.com/WebServiceCotizadorInterface/obtenerCoberturasConjuntoVHResponse")
    public String obtenerCoberturasConjuntoVH();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "retorno", partName = "retorno")
    @Action(input = "http://cotizador.interfaces.servicios.qbe.com/WebServiceCotizadorInterface/obtenerDetallesProductoRequest", output = "http://cotizador.interfaces.servicios.qbe.com/WebServiceCotizadorInterface/obtenerDetallesProductoResponse")
    public String obtenerDetallesProducto();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "retorno", partName = "retorno")
    @Action(input = "http://cotizador.interfaces.servicios.qbe.com/WebServiceCotizadorInterface/obtenerPlanesRequest", output = "http://cotizador.interfaces.servicios.qbe.com/WebServiceCotizadorInterface/obtenerPlanesResponse")
    public String obtenerPlanes();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "retorno", partName = "retorno")
    @Action(input = "http://cotizador.interfaces.servicios.qbe.com/WebServiceCotizadorInterface/obtenerCoberturaDetalleProductoRequest", output = "http://cotizador.interfaces.servicios.qbe.com/WebServiceCotizadorInterface/obtenerCoberturaDetalleProductoResponse")
    public String obtenerCoberturaDetalleProducto();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://cotizador.interfaces.servicios.qbe.com/WebServiceCotizadorInterface/obtenerCoberturasConjuntoRequest", output = "http://cotizador.interfaces.servicios.qbe.com/WebServiceCotizadorInterface/obtenerCoberturasConjuntoResponse")
    public String obtenerCoberturasConjunto();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "retorno", partName = "retorno")
    @Action(input = "http://cotizador.interfaces.servicios.qbe.com/WebServiceCotizadorInterface/obtenerConfiguracionProductoRequest", output = "http://cotizador.interfaces.servicios.qbe.com/WebServiceCotizadorInterface/obtenerConfiguracionProductoResponse")
    public String obtenerConfiguracionProducto();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "retorno", partName = "retorno")
    @Action(input = "http://cotizador.interfaces.servicios.qbe.com/WebServiceCotizadorInterface/obtenerDeduciblesRequest", output = "http://cotizador.interfaces.servicios.qbe.com/WebServiceCotizadorInterface/obtenerDeduciblesResponse")
    public String obtenerDeducibles();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "retorno", partName = "retorno")
    @Action(input = "http://cotizador.interfaces.servicios.qbe.com/WebServiceCotizadorInterface/obtenerConjuntoCoberurasRequest", output = "http://cotizador.interfaces.servicios.qbe.com/WebServiceCotizadorInterface/obtenerConjuntoCoberurasResponse")
    public String obtenerConjuntoCoberuras();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "retorno", partName = "retorno")
    @Action(input = "http://cotizador.interfaces.servicios.qbe.com/WebServiceCotizadorInterface/obtenerConfiguracionProductosVHRequest", output = "http://cotizador.interfaces.servicios.qbe.com/WebServiceCotizadorInterface/obtenerConfiguracionProductosVHResponse")
    public String obtenerConfiguracionProductosVH();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "retorno", partName = "retorno")
    @Action(input = "http://cotizador.interfaces.servicios.qbe.com/WebServiceCotizadorInterface/obtenerEntidadesJrRequest", output = "http://cotizador.interfaces.servicios.qbe.com/WebServiceCotizadorInterface/obtenerEntidadesJrResponse")
    public String obtenerEntidadesJr();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "retorno", partName = "retorno")
    @Action(input = "http://cotizador.interfaces.servicios.qbe.com/WebServiceCotizadorInterface/obtenerFirmasDigitalesRequest", output = "http://cotizador.interfaces.servicios.qbe.com/WebServiceCotizadorInterface/obtenerFirmasDigitalesResponse")
    public String obtenerFirmasDigitales();

    /**
     * 
     * @param sucursal
     * @param entidad
     * @param ramo
     * @return
     *     returns byte[]
     */
    @WebMethod
    @WebResult(name = "retorno", partName = "retorno")
    @Action(input = "http://cotizador.interfaces.servicios.qbe.com/WebServiceCotizadorInterface/obtenerFirmasDigitalesParametrosRequest", output = "http://cotizador.interfaces.servicios.qbe.com/WebServiceCotizadorInterface/obtenerFirmasDigitalesParametrosResponse")
    public byte[] obtenerFirmasDigitalesParametros(
        @WebParam(name = "sucursal", partName = "sucursal")
        String sucursal,
        @WebParam(name = "entidad", partName = "entidad")
        String entidad,
        @WebParam(name = "ramo", partName = "ramo")
        String ramo);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "retorno", partName = "retorno")
    @Action(input = "http://cotizador.interfaces.servicios.qbe.com/WebServiceCotizadorInterface/obtenerAurotizacionesSRIRequest", output = "http://cotizador.interfaces.servicios.qbe.com/WebServiceCotizadorInterface/obtenerAurotizacionesSRIResponse")
    public String obtenerAurotizacionesSRI();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "retorno", partName = "retorno")
    @Action(input = "http://cotizador.interfaces.servicios.qbe.com/WebServiceCotizadorInterface/obtenerTipoExtraRequest", output = "http://cotizador.interfaces.servicios.qbe.com/WebServiceCotizadorInterface/obtenerTipoExtraResponse")
    public String obtenerTipoExtra();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "retorno", partName = "retorno")
    @Action(input = "http://cotizador.interfaces.servicios.qbe.com/WebServiceCotizadorInterface/obtenerMarcasVehiculoRequest", output = "http://cotizador.interfaces.servicios.qbe.com/WebServiceCotizadorInterface/obtenerMarcasVehiculoResponse")
    public String obtenerMarcasVehiculo();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "retorno", partName = "retorno")
    @Action(input = "http://cotizador.interfaces.servicios.qbe.com/WebServiceCotizadorInterface/obtenerColoresVehiculoRequest", output = "http://cotizador.interfaces.servicios.qbe.com/WebServiceCotizadorInterface/obtenerColoresVehiculoResponse")
    public String obtenerColoresVehiculo();

    /**
     * 
     * @param numeroFactura
     * @param numeroTramite
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(name = "retorno", partName = "retorno")
    @Action(input = "http://cotizador.interfaces.servicios.qbe.com/WebServiceCotizadorInterface/guardarNumeroTramiteEndosoRequest", output = "http://cotizador.interfaces.servicios.qbe.com/WebServiceCotizadorInterface/guardarNumeroTramiteEndosoResponse")
    public boolean guardarNumeroTramiteEndoso(
        @WebParam(name = "numeroFactura", partName = "numeroFactura")
        String numeroFactura,
        @WebParam(name = "numeroTramite", partName = "numeroTramite")
        String numeroTramite);

}
