
package com.qbe.cotizador.servicios.QBE.clienteServiciosCotizador;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WebServiceCotizadorPymesInterface", targetNamespace = "http://cotizador.interfaces.servicios.qbe.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface WebServiceCotizadorPymesInterface {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "retorno", partName = "retorno")
    @Action(input = "http://cotizador.interfaces.servicios.qbe.com/WebServiceCotizadorPymesInterface/obtenerCoberturasRequest", output = "http://cotizador.interfaces.servicios.qbe.com/WebServiceCotizadorPymesInterface/obtenerCoberturasResponse")
    public String obtenerCoberturas(String ramo);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "retorno", partName = "retorno")
    @Action(input = "http://cotizador.interfaces.servicios.qbe.com/WebServiceCotizadorPymesInterface/obtenerProductosRequest", output = "http://cotizador.interfaces.servicios.qbe.com/WebServiceCotizadorPymesInterface/obtenerProductosResponse")
    public String obtenerProductos(String ramo);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "retorno", partName = "retorno")
    @Action(input = "http://cotizador.interfaces.servicios.qbe.com/WebServiceCotizadorPymesInterface/obtenerGruposCoberturaRequest", output = "http://cotizador.interfaces.servicios.qbe.com/WebServiceCotizadorPymesInterface/obtenerGruposCoberturaResponse")
    public String obtenerGruposCobertura(String ramo);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "retorno", partName = "retorno")
    @Action(input = "http://cotizador.interfaces.servicios.qbe.com/WebServiceCotizadorPymesInterface/obtenerConjuntoCoberturasRequest", output = "http://cotizador.interfaces.servicios.qbe.com/WebServiceCotizadorPymesInterface/obtenerConjuntoCoberturasResponse")
    public String obtenerConjuntoCoberturas(String ramo);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "retorno", partName = "retorno")
    @Action(input = "http://cotizador.interfaces.servicios.qbe.com/WebServiceCotizadorPymesInterface/obtenerDetallesProductoRequest", output = "http://cotizador.interfaces.servicios.qbe.com/WebServiceCotizadorPymesInterface/obtenerDetallesProductoResponse")
    public String obtenerDetallesProducto();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "retorno", partName = "retorno")
    @Action(input = "http://cotizador.interfaces.servicios.qbe.com/WebServiceCotizadorPymesInterface/obtenerCoberturaDetalleProductoRequest", output = "http://cotizador.interfaces.servicios.qbe.com/WebServiceCotizadorPymesInterface/obtenerCoberturaDetalleProductoResponse")
    public String obtenerCoberturaDetalleProducto(String ramo);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "retorno", partName = "retorno")
    @Action(input = "http://cotizador.interfaces.servicios.qbe.com/WebServiceCotizadorPymesInterface/obtenerCoberturasConjuntoRequest", output = "http://cotizador.interfaces.servicios.qbe.com/WebServiceCotizadorPymesInterface/obtenerCoberturasConjuntoResponse")
    public String obtenerCoberturasConjunto(String ramo);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "retorno", partName = "retorno")
    @Action(input = "http://cotizador.interfaces.servicios.qbe.com/WebServiceCotizadorPymesInterface/obtenerConfiguracionProductoRequest", output = "http://cotizador.interfaces.servicios.qbe.com/WebServiceCotizadorPymesInterface/obtenerConfiguracionProductoResponse")
    public String obtenerConfiguracionProducto(String ramo);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "retorno", partName = "retorno")
    @Action(input = "http://cotizador.interfaces.servicios.qbe.com/WebServiceCotizadorPymesInterface/obtenerPlanesRequest", output = "http://cotizador.interfaces.servicios.qbe.com/WebServiceCotizadorPymesInterface/obtenerPlanesResponse")
    public String obtenerPlanes();
    
    
    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "retorno", partName = "retorno")
    @Action(input = "http://cotizador.interfaces.servicios.qbe.com/WebServiceCotizadorPymesInterface/obtenerDeduciblesRequest", output = "http://cotizador.interfaces.servicios.qbe.com/WebServiceCotizadorPymesInterface/obtenerDeduciblesResponse")
    public String obtenerDeducibles(String ramo);
}
