
package com.qbe.cotizador.servicios.QBE.clienteServiciosCotizador;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import com.qbe.cotizador.dao.seguridad.VariableSistemaDAO;
import com.qbe.cotizador.model.VariableSistema;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WebServiceCotizadorPymesImplService", targetNamespace = "http://cotizador.implementacion.servicios.qbe.com/", wsdlLocation = "http://10.10.21.116:8080/servicios/cotizadorPymes?wsdl")
public class WebServiceCotizadorPymesImplService
    extends Service
{

    private final static URL WEBSERVICECOTIZADORPYMESIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException WEBSERVICECOTIZADORPYMESIMPLSERVICE_EXCEPTION;
    private final static QName WEBSERVICECOTIZADORPYMESIMPLSERVICE_QNAME = new QName("http://cotizador.implementacion.servicios.qbe.com/", "WebServiceCotizadorPymesImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
        	VariableSistemaDAO variableSistemaDAO = new VariableSistemaDAO();
        	VariableSistema variableSistema = variableSistemaDAO.buscarPorNombre("URL_SERVICIOS_COTIZADOR_PYMES");
        	url = new URL(variableSistema.getValor());        	            
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WEBSERVICECOTIZADORPYMESIMPLSERVICE_WSDL_LOCATION = url;
        WEBSERVICECOTIZADORPYMESIMPLSERVICE_EXCEPTION = e;
    }

    public WebServiceCotizadorPymesImplService() {
        super(__getWsdlLocation(), WEBSERVICECOTIZADORPYMESIMPLSERVICE_QNAME);
    }

    public WebServiceCotizadorPymesImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WEBSERVICECOTIZADORPYMESIMPLSERVICE_QNAME, features);
    }

    public WebServiceCotizadorPymesImplService(URL wsdlLocation) {
        super(wsdlLocation, WEBSERVICECOTIZADORPYMESIMPLSERVICE_QNAME);
    }

    public WebServiceCotizadorPymesImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WEBSERVICECOTIZADORPYMESIMPLSERVICE_QNAME, features);
    }

    public WebServiceCotizadorPymesImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebServiceCotizadorPymesImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WebServiceCotizadorPymesInterface
     */
    @WebEndpoint(name = "WebServiceCotizadorPymesImplPort")
    public WebServiceCotizadorPymesInterface getWebServiceCotizadorPymesImplPort() {
        return super.getPort(new QName("http://cotizador.implementacion.servicios.qbe.com/", "WebServiceCotizadorPymesImplPort"), WebServiceCotizadorPymesInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebServiceCotizadorPymesInterface
     */
    @WebEndpoint(name = "WebServiceCotizadorPymesImplPort")
    public WebServiceCotizadorPymesInterface getWebServiceCotizadorPymesImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://cotizador.implementacion.servicios.qbe.com/", "WebServiceCotizadorPymesImplPort"), WebServiceCotizadorPymesInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WEBSERVICECOTIZADORPYMESIMPLSERVICE_EXCEPTION!= null) {
            throw WEBSERVICECOTIZADORPYMESIMPLSERVICE_EXCEPTION;
        }
        return WEBSERVICECOTIZADORPYMESIMPLSERVICE_WSDL_LOCATION;
    }

}
