
package com.qbe.cotizador.servicios.QBE.clienteServiciosCotizador;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import com.qbe.cotizador.dao.seguridad.VariableSistemaDAO;
import com.qbe.cotizador.model.VariableSistema;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WebServiceCotizadorAgricolaImplService", targetNamespace = "http://cotizador.implementacion.servicios.qbe.com/", wsdlLocation = "http://10.10.21.116:8080/servicios/cotizadorAgricola?wsdl")
public class WebServiceCotizadorAgricolaImplService
    extends Service
{

    private final static URL WEBSERVICECOTIZADORAGRICOLAIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException WEBSERVICECOTIZADORAGRICOLAIMPLSERVICE_EXCEPTION;
    private final static QName WEBSERVICECOTIZADORAGRICOLAIMPLSERVICE_QNAME = new QName("http://cotizador.implementacion.servicios.qbe.com/", "WebServiceCotizadorAgricolaImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
        	VariableSistemaDAO variableSistemaDAO = new VariableSistemaDAO();
        	VariableSistema variableSistema = variableSistemaDAO.buscarPorNombre("URL_SERVICIOS_COTIZADOR_AGRICOLA");
        	url = new URL(variableSistema.getValor());
        	            
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WEBSERVICECOTIZADORAGRICOLAIMPLSERVICE_WSDL_LOCATION = url;
        WEBSERVICECOTIZADORAGRICOLAIMPLSERVICE_EXCEPTION = e;
    }

    public WebServiceCotizadorAgricolaImplService() {
        super(__getWsdlLocation(), WEBSERVICECOTIZADORAGRICOLAIMPLSERVICE_QNAME);
    }

    public WebServiceCotizadorAgricolaImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WEBSERVICECOTIZADORAGRICOLAIMPLSERVICE_QNAME, features);
    }

    public WebServiceCotizadorAgricolaImplService(URL wsdlLocation) {
        super(wsdlLocation, WEBSERVICECOTIZADORAGRICOLAIMPLSERVICE_QNAME);
    }

    public WebServiceCotizadorAgricolaImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WEBSERVICECOTIZADORAGRICOLAIMPLSERVICE_QNAME, features);
    }

    public WebServiceCotizadorAgricolaImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebServiceCotizadorAgricolaImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WebServiceCotizadorAgricolaInterface
     */
    @WebEndpoint(name = "WebServiceCotizadorAgricolaImplPort")
    public WebServiceCotizadorAgricolaInterface getWebServiceCotizadorAgricolaImplPort() {
        return super.getPort(new QName("http://cotizador.implementacion.servicios.qbe.com/", "WebServiceCotizadorAgricolaImplPort"), WebServiceCotizadorAgricolaInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebServiceCotizadorAgricolaInterface
     */
    @WebEndpoint(name = "WebServiceCotizadorAgricolaImplPort")
    public WebServiceCotizadorAgricolaInterface getWebServiceCotizadorAgricolaImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://cotizador.implementacion.servicios.qbe.com/", "WebServiceCotizadorAgricolaImplPort"), WebServiceCotizadorAgricolaInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WEBSERVICECOTIZADORAGRICOLAIMPLSERVICE_EXCEPTION!= null) {
            throw WEBSERVICECOTIZADORAGRICOLAIMPLSERVICE_EXCEPTION;
        }
        return WEBSERVICECOTIZADORAGRICOLAIMPLSERVICE_WSDL_LOCATION;
    }

}
